spring:
  application:
    name: webScraper
  kafka:
    bootstrap-servers: 13.125.55.123:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: web-scraper

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menu?serverTimezone=UTC
    username: root
    password: test123


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
